### PR TITLE
Development

### PR DESCRIPTION
**Pull request by dipto0321**
Hi @Skobraf,
@rvvergara  and I complete this project. Please give us feedback after check out.
Thanks

### CODE REVIEW

**Comment by talihomz** [comment]
Hi @dipto0321 @rvvergara!

I'l be taking care of reviewing this for you guys.

**Comment by Skobraf** [comment]
Hi Kevin! Thank you for your help

**Comment by talihomz** [comment]
Hi @Skobraf! You're welcome :-)

**Comment by talihomz** [comment]
@dipto0321 @rvvergara I'm having some issues setting up your project on my local machine(changing authentication configs in my local DB). Will ping you tomorrow when I have this sorted out.

**Comment by dipto0321** [comment]
Thanks, Kevin!
No problem take your time.

**Comment by talihomz** [comment]
Hi @dipto0321 @rvvergara !

I finally setup my environment and run your project. I think you have done a great job on this one!

A couple of things I wanted to note on using the app:
1. 4 tests failed upon doing `rake test`.
2. I know you are comfortable with using Minitest on this project. However, have a look at [RSpec](http://rspec.info/) which is more widely used. This is the testing framework out team and others have used during testing so far.
3. After a successful login, I clicked on "Profile" and this happened:
screenshot from 2018-12-10 03-14-19

I couldn't do more of the review of Ui after the above error. Let me know when this is fixed, so that I can add a few more thoughts. Otherwise, this was well executed so far guys, keep it up!

**Pull request merged**
